---
- name: Download and unzip a file
  hosts: localhost
  tasks:
    - name: Download the ZIP file
      get_url:
        url: https://getsamplefiles.com/download/zip/sample-1.zip
        dest: file.zip
        mode: '0644'

    - name: Ensure the target directory exists
      file:
        path: output
        state: directory
        mode: '0755'

    - name: Unzip the file
      unarchive:
        src: file.zip
        dest: output
