---
- name: Download and unzip a file
  hosts: localhost
  tasks:
  - name: Unzip the file using shell
    shell: unzip sample-1.zip -d .

  - name: List extracted files
    find:
      paths: .
    register: extracted_files

  - name: Display file names only
    debug:
      msg: "{{ item.path | basename }}"
    loop: "{{ extracted_files.files }}"